### PR TITLE
Extend vue/nuxt/vuex interfaces to provide proper types for $ua

### PR DESCRIPTION
**Pull request by rchl**
- Extended vue/nuxt/vuex module interfaces with $ua object with proper
type.
- Added Nuxt as devDependency and remove explicit devDependencies on
vue-router, vuex, etc. as Nuxt already includes those.
- Use `Context` type from `@nuxt/types` instead of custom one.
- Add `types` endpoint in `package.json`

### CODE REVIEW

**Comment by rchl** [comment]
This should probably be consider a braking change as `UA` type is no longer exported as there is no need for that as every place that has that object is already extended.

**Comment by rchl** [comment]
Also, `examples/typescript` uses very outdated way of using typescript in nuxt and also it's wrong in various places. I can either remove it or update to latest nuxt but I'm not sure if there is much value in it.

**Comment by rchl** [comment]
@fukuiretu ping

**Comment by rchl** [comment]
I'm not losing hope yet :)

**Review by atinux — APPROVED** [review]

**Comment by atinux** [comment]
Friendly ping @fukuiretu

**Comment by rchl** [comment]
@fukuiretu How do you think we can proceed here?

Maybe if you don't want to maintain it then you could transfer it to nuxt-community (if @Atinux agrees).

**Pull request closed without merging**
